// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqtqmmlqqozthjzhkgdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxdHFtbWxxcW96dGhqemhrZ2RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNzc2MzEsImV4cCI6MjA1NDY1MzYzMX0.ClGELTHp4V1zh3f9V8XmTYfgqpU-DZCrDKvzRsGHheg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);